### ISSUE TITLE
Prevent dyno idling in 30 minites?

### ISSUE THREAD

**Issue by ktownag** [developeranaz/qbittorrent-to-rclone-heroku#14]
Heroku's free dyno will idle when there is no incoming request within 30 minutes, and your files will be deleted too.
There is a similar but outdated repo that can generate fake requests when there are downloading or uploading tasks, so it won't idle when your files aren't completed. See here https://github.com/maple3142/aria2c-ariang 
The working codes are included in the index.js file of that repo.
Is it possible to do that to qbittorrent?
Thanks!

**Comment by developeranaz** [comment]
I did made it on another branch , now i applied that update
redeploy it and use `selfping` corresponding `app-name` as env-vars section in heroku

eg: 
![-4962988908900100631_121](https://user-images.githubusercontent.com/71500526/158632565-d202af3f-5bc1-4630-8d0a-83bce88cb18f.jpg)

**Comment by ktownag** [comment]
Great. Would be better if selfping stops automatically when downloads complete.
