### ISSUE TITLE
Heroku: Unable to Deploy

### ISSUE THREAD

**Issue by TheCaduceus** [developeranaz/qbittorrent-to-rclone-heroku#21]
Facing below Error while deploying on Heroku
----

=== Fetching app code
=== Building web (Dockerfile)
Sending build context to Docker daemon  1.144MBStep 1/8 : FROM developeranaz/qbittorrent2rclone:beta1
beta1: Pulling from developeranaz/qbittorrent2rclone
7b1a6ab2e44d: Pulling fs layer
cbe65838fd00: Pulling fs layer
612025a63962: Pulling fs layer
7b1a6ab2e44d: Verifying Checksum
7b1a6ab2e44d: Download complete
612025a63962: Verifying Checksum
612025a63962: Download complete
cbe65838fd00: Verifying Checksum
cbe65838fd00: Download complete
7b1a6ab2e44d: Pull complete
cbe65838fd00: Pull complete
612025a63962: Pull complete
Digest: sha256:e708dc1e58914524fbeddf6ef8e307332370ac5b5a2c9476005a827590443ea9
Status: Downloaded newer image for developeranaz/qbittorrent2rclone:beta1
 ---> 248e355ca908
Step 2/8 : RUN apt install supervisor -y
 ---> Running in 47645ecca159
The following additional packages will be installed:
  file libmagic-mgc libmagic1 libmpdec2 libpython3-stdlib libpython3.8-minimal
  libpython3.8-stdlib libreadline8 mime-support python3 python3-minimal
  python3-pkg-resources python3.8 python3.8-minimal readline-common xz-utils
Suggested packages:
  python3-doc python3-tk python3-venv python3-setuptools python3.8-venv
  python3.8-doc binutils binfmt-support readline-doc supervisor-doc
The following NEW packages will be installed:
  file libmagic-mgc libmagic1 libmpdec2 libpython3-stdlib libpython3.8-minimal
  libpython3.8-stdlib libreadline8 mime-support python3 python3-minimal
  python3-pkg-resources python3.8 python3.8-minimal readline-common supervisor
  xz-utils
0 upgraded, 17 newly installed, 0 to remove and 0 not upgraded.
Need to get 5864 kB of archives.
After this operation, 29.2 MB of additional disk space will be used.
Get:13 http://archive.ubuntu.com/ubuntu focal/universe amd64 supervisor all 4.1.0-1ubuntu1 [281 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal/main amd64 libmagic1 amd64 1:5.38-4 [75.9 kB]
  404  Not Found [IP: 91.189.91.39 80]
  404  Not Found [IP: 91.189.91.39 80]
  404  Not Found [IP: 91.189.91.39 80]
  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.8/libpython3.8-minimal_3.8.10-0ubuntu1~20.04.2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.8/python3.8-minimal_3.8.10-0ubuntu1~20.04.2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.8/libpython3.8-stdlib_3.8.10-0ubuntu1~20.04.2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.8/python3.8_3.8.10-0ubuntu1~20.04.2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt install supervisor -y' returned a non-zero code: 100

**Comment by developeranaz** [comment]
I think package manager's server or heroku is facing some serious issues. Try installing Again or try after sometimes.

**Comment by TheCaduceus** [comment]
> I think package manager's server or heroku is facing some serious issues. Try installing Again or try after sometimes.

Yes, I tried it after sometimes. But still showing the same.

**Comment by developeranaz** [comment]
> > I think package manager's server or heroku is facing some serious issues. Try installing Again or try after sometimes.
> 
> Yes, I tried it after sometimes. But still showing the same.

fixed

**Comment by TheCaduceus** [comment]
Thanks

> > > I think package manager's server or heroku is facing some serious issues. Try installing Again or try after sometimes.
> > 
> > 
> > Yes, I tried it after sometimes. But still showing the same.
> 
> Fixed Try redeploying again

Thanks! Now it is fixed
