### ISSUE TITLE
Vercel

### ISSUE THREAD

**Issue by Itz-Ayanokoji** [developeranaz/qbittorrent-to-rclone-heroku#32]
How about deploy the repo on vercel?

**Comment by developeranaz** [comment]
I think vercel is serverless.

**Comment by Itz-Ayanokoji** [comment]
> I think vercel is serverless. like cloudflare workers. so it may not possible.

Any other thing then? Cause I need this repo working very badly

**Comment by developeranaz** [comment]
currently there is't any way.Try using Google colab.

**Comment by Itz-Ayanokoji** [comment]
> currently there is't any way.Try using Google colab. 

Try Scalingo pls.. I request you

**Comment by developeranaz** [comment]
only 30day free trial 😅

**Comment by developeranaz** [comment]
okey, but i don't have time to rebuilt this now.
i'll fix them when i get time.
