### ISSUE TITLE
Storing

### ISSUE THREAD

**Issue by Itz-Ayanokoji** [developeranaz/qbittorrent-to-rclone-heroku#38]
Can you please tell me where the files are stored after I downloaded the content?

**Comment by developeranaz** [comment]
Files are stored in Heroku's storage. and you need to download it before it gets deleted.

**Comment by Itz-Ayanokoji** [comment]
How can I download?

**Comment by developeranaz** [comment]
After downloading the torrent in qbittorrent
go to https://yourappname.herokuapp.com/downloads/downloads/ you will see your downloaded file.

**Comment by Itz-Ayanokoji** [comment]
> > After downloading the torrent in qbittorrent go to https://yourappname.herokuapp.com/downloads/downloads/ you will see your downloaded file.
> 
> we cant use rclone raw url to upload to gdrive directly?

It gets banned that's the problem bruh

**Comment by developeranaz** [comment]
Because of the Rclone ban, uploading to remotes is currently disabled. 
You need to repload to clouds using other services like colab uploaders.

**Comment by Itz-Ayanokoji** [comment]
> 

Do you have any Telegram bot for that atleast?

**Comment by askfriends** [comment]
> Because of the Rclone ban, uploading to remotes is currently disabled. You need to repload to clouds using other services like colab uploaders.

oh alright, but is there any way to zip or tar downloads?
it will be easy to upload single files rather than huge number of files like music

**Comment by developeranaz** [comment]
currently i did't added anything about this zip or tar.
but indirectly i had a method. but its complicated

**Comment by askfriends** [comment]
> currently i did't added anything about this zip or tar. but indirectly i had a method. but its complicated

will u plz explain it or add it to current repo?
bcoz im downloading some huge music files, and i cant upload them to gdrive individually.

**Comment by developeranaz** [comment]
> Do you have any Telegram bot for that atleast?

i suggest colab may be fast than other telegram bot.

**Comment by developeranaz** [comment]
> > currently i did't added anything about this zip or tar. but indirectly i had a method. but its complicated
> 
> will u plz explain it or add it to current repo? bcoz im downloading some huge music files, and i cant upload them to gdrive individually.

wait,
the method is to zip the whole downloads folder .

**Comment by askfriends** [comment]
> > > currently i did't added anything about this zip or tar. but indirectly i had a method. but its complicated
> > 
> > 
> > will u plz explain it or add it to current repo? bcoz im downloading some huge music files, and i cant upload them to gdrive individually.
> 
> wait, the method is to zip the whole downloads folder .

yeah that will be helpful ig.

**Comment by developeranaz** [comment]
![IMG_20221013_195010](https://user-images.githubusercontent.com/71500526/195623805-48ee2b4a-c341-4933-b09a-a7be40dc32a6.jpg)


![IMG_20221013_195150](https://user-images.githubusercontent.com/71500526/195624062-2dbae466-4b92-4b10-a029-c3d5ea16bdb3.jpg)

```
zip -r /qBittorrent/downloadedbundle.zip /qBittorrent/downloads; curl -L "https://api.telegram.org/bot000000xxxx0000/sendMessage?chat_id=xxxxxxx&text=filezipped"
```

you can edit above telegram bot alert value if needed its optional.

After the above steps add a final torrent (means you need to add a sample torrent and it need to be completed ) 

After a final torrent competed your folder starts to create zip.

wait for the zip gets ceated. (based on file size)

then check https://yourapp.herokuapp.com/downloads/

![IMG_20221013_195932](https://user-images.githubusercontent.com/71500526/195626339-dbdeb0b4-1f5b-4225-95fa-74ea95b950bb.jpg)

**Comment by Itz-Ayanokoji** [comment]
> > Do you have any Telegram bot for that atleast?
> 
> i suggest colab may be fast than other telegram bot.

Ahh.. okay
