### ISSUE TITLE
Why torrent gets deleted after few hours?

### ISSUE THREAD

**Issue by askfriends** [developeranaz/qbittorrent-to-rclone-heroku#6]
Torrent gets deleted after few hours, how to fix that?
is that due to app sleeping?

**Comment by developeranaz** [comment]
maybe of app sleep -use heroku kaffine

**Comment by askfriends** [comment]
> kaffine

yeah but can u add that feature so tht it never gets sleep?
most mirror bots has that feature, there is var in config where we put app name and it pings it after specified time, you can take that code from there.

**Comment by developeranaz** [comment]
i did had samples but not tested enough, and currently i'mm trying to make something new😊

try posting issues.

**Comment by askfriends** [comment]
> i did had samples but not tested enough, and currently i'mm trying to make something new😊
> 
> try posting issues.

would luv to see that ""NEW THING

**Comment by AmirulAndalib** [comment]
is this a fcking joke 😂 heroku storage is not persistent its ephemeral drive it will always get deleted after 14-18 hours stop your nonsense joke

**Comment by askfriends** [comment]
> is this a joke 😂 heroku storage is not persistent its ephemeral drive it will always get deleted after 14-18 hours stop your nonsense joke

are u in ur senses?
im not saying abiut that but files/torrents get deleted after 2 or 3 hours, thats different than 24hrs as heroku policy

**Comment by AmirulAndalib** [comment]
Ok then it's confirmed bot needs a pinger

**Comment by askfriends** [comment]
> Ok then it's confirmed bot needs a pinger

yeah.

**Comment by developeranaz** [comment]
> Ok then it's confirmed bot needs a pinger

added
