### ISSUE TITLE
Please upload in a new folder for each torrent

### ISSUE THREAD

**Issue by avasthi-git** [developeranaz/qbittorrent-to-rclone-heroku#8]
The torrents are uploaded in a folder named qbit, in root/qbit/ only.
Please make it root/qbit/{Torrent Name}/
So that its easy to search files.

**Comment by developeranaz** [comment]
ok i'll pull that patch

**Comment by developeranaz** [comment]
fixed
https://github.com/developeranaz/qbittorrent-to-rclone-heroku/pull/7
