### ISSUE TITLE
Error: Bot Not Starting

### ISSUE THREAD

**Issue by missemily2022** [developeranaz/qbittorrent-to-rclone-heroku#9]
![image](https://user-images.githubusercontent.com/97376138/151806574-d94afad2-ae6a-4852-b1fc-9d8690ab395c.png)

**Comment by developeranaz** [comment]
use rapid deployment button for deployment
 [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://developeranaz.github.io/qbittorrent-to-rclone-heroku/random.html)

**Comment by missemily2022** [comment]
@developeranaz Bro I know its for webapp but the App only boots if I keep the default value of username password and rclone config in the heroku vars if I change them the bot does not boot anymore  And yes I have used your rapid Deployment Button only

**Comment by developeranaz** [comment]
You can share your configuration after hiding your credentials ,
maybe your rclone config name is the problem.
make it simple eg `[devanaz]` anyway share your hided config .
or use simple username and password for qbweb

**Comment by developeranaz** [comment]
![Uploading Screenshot_20220208_084938.jpg…]()
This is my config var, please change it similar to this for temporary testing.

**Comment by missemily2022** [comment]
@developeranaz Wait I am trying your Config now

**Comment by missemily2022** [comment]
@developeranaz 
![image](https://user-images.githubusercontent.com/97376138/152938538-e8fbcc00-b874-4e9f-a63c-2c524384e558.png)
![image](https://user-images.githubusercontent.com/97376138/152938583-591c18ed-766e-4e79-a3d9-92a6444b7ce9.png)

**Comment by developeranaz** [comment]
I don't know why the app crashes.
Please re-check all your configuration whether it is working locally in your device and redeploy one last time.

Maybe the configuration you are using may not recognize or match the latest version of rclone. 
I tested this with my personal onedrive account and it worked. But I haven't tested it with a onedrive business account.
Or You can try the test using any other remotes or cloud provided by rclone.

**Comment by missemily2022** [comment]
@developeranaz Thanks
